### ISSUE TITLE
Issue with server

### ISSUE THREAD

**Issue by KadePcGames** [iLinked-is-a-meme/chat-application#1]
On making a new server it fails.
Cant make a pull request so il put the files to fix it here:
also added some console feedback.
[Program.zip](https://github.com/iLinked-is-a-meme/chat-application/files/2490312/Program.zip)

**Comment by iLinked-is-a-meme** [comment]
Right, should've fixed that by now lol. would you like to work together with me on this shite?

**Comment by iLinked-is-a-meme** [comment]
fixed it basically
